# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PondasiContracts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PondasiContracts

  target 'PondasiContractsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PondasiContractsUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
