platform :ios, '17.0'
use_frameworks!

target 'WorkoutApp' do
  # Link to the shared core from the perspective of this folder
  pod 'PondasiContracts', :path => '../../Core/PondasiContracts'
end

post_install do |installer|
  # Disable sandboxing for all Pod targets
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end

  # Disable sandboxing for the main app target as well
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
    aggregate_target.user_project.save
  end
end