platform :ios, '17.0'
use_frameworks!

# Use path-based development pods for the monorepo
target 'PondasiApp' do
  pod 'PondasiContracts', :path => '../Core/PondasiContracts'
  pod 'CreativityApp',    :path => '../Apps/CreativityApp'
  pod 'WorkoutApp',       :path => '../Apps/WorkoutApp'
  pod 'JournalApp',       :path => '../Apps/JournalApp'

  target 'PondasiAppTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
    aggregate_target.user_project.save
  end
end