platform :ios, '17.0'
use_frameworks!

target 'JournalApp' do
  # Link to the shared core from the perspective of this folder
  pod 'PondasiContracts', :path => '../../Core/PondasiContracts'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end